### ISSUE TITLE
so much green

### ISSUE THREAD

**Issue by mnlgn** [linuxmint/mint-themes-gtk3#67]
![bildschirmfoto vom 2016-01-02 03 34 26](https://cloud.githubusercontent.com/assets/1057526/12072966/447c0e3c-b102-11e5-85f5-b7af6f6354a2.png)

**Comment by JosephMcc** [comment]
Sorry, I don't understand the point of this issue. Is the theme broken? Does it look like that with the default theme? Did you do/want something to make it look like that?

**Comment by mnlgn** [comment]
Yes it looks broken compared to the screenshots. I had to change the theme once to adwaita and switched back to some mint theme, now the background is white as expected. Dont know why this behaviour happens with linux mint 17.3.
