### ISSUE TITLE
Request: include a clearlooks-like theme

### ISSUE THREAD

**Issue by windy32** [linuxmint/mint-themes-gtk3#76]
Clearlooks-phoenix looks great under Linux Mint 17.2 / MATE, but something looks strange under Linux Mint 18 / MATE.

I hope that a clearlooks-like theme could be tested and included by default when Linux Mint is installed

**Comment by windy32** [comment]
For more details, see https://github.com/linuxmint/xed/issues/22

**Comment by JosephMcc** [comment]
Your theme likely isn't properly updated for gtk3.18. I don't see us supporting any more themes any time soon outside of maybe color variations of the Mint-Y like we do for Mint-X.

**Comment by GLolol** [comment]
Clearlooks-phenix hasn't been ported to GTK 3.18. If you want something that looks similar, install `mate-themes` and try the TraditionalOk theme there.
