### ISSUE TITLE
Weird look in Debian with Cinnamon

### ISSUE THREAD

**Issue by vivek-roy** [linuxmint/mint-themes-gtk3#81]
![screenshot from 2017-04-10 20-01-10](https://cloud.githubusercontent.com/assets/20724374/24866671/7d0fcd80-1e28-11e7-98af-82a02c199c4c.png)
On downloading mint-themes (master) and mint-themes-gtk3 (master) and copying them into ~/.themes folder, on applying the mint-x controls the controls become weird looking (as shown in the screenshot).

**Comment by JosephMcc** [comment]
These themes are designed for use in Mint. That means Mint18 and LMDE2. They won't work on distros using gtk versions >= 3.20. They will eventually but we don't need the support in Mint currently so it isn't a priority.

**Comment by dodona2** [comment]
I confirm that strange behavior for Fedora 25.
