### ISSUE TITLE
All of the Mint-X themes show unreadable menus in particular cases

### ISSUE THREAD

**Issue by drakej** [linuxmint/mint-themes-gtk3#83]
I've noticed that only the Mint-X themes exhibit a symptom where context menus show up with white text on a background of very light grey. Mint-Y themes and other GTK3 themes don't exhibit this problem.

I can reproduce this by installing Evolution, applying any theme custom or note on Mate that utilizes Mint-X or a subvariant of Mint-X's controls. 

Essentially the issue exists within the controls aspect of all Mint-X themes.

**Comment by JosephMcc** [comment]
> I can reproduce this by installing Evolution, applying any theme custom or note on Mate that utilizes Mint-X or a subvariant of Mint-X's controls.

Sorry but I don't really understand that sentence. Can you give a specific example of a context menu that doesn't work? Also please include the OS and version you're running.

**Comment by drakej** [comment]
![mint-x-issue](https://user-images.githubusercontent.com/952345/26983167-baab2fb8-4cef-11e7-8161-9380881ba119.png)

So this is a screenshot where the menu isn't working as expected. The current theme in use is Mint-X Aqua. The application in evolution as I mentioned. In this case 3.18.5.2, however a coworker with the same version didn't show these problems with his theming in Unity on Ubuntu. I'm running Linux Mint 18.1 MATE edition in this case. I only get this issue in evolution from the Mint-X themes. Mint-Y and other themes don't show white text on a light grey background.

**Comment by JosephMcc** [comment]
Thanks for following up. I'll look into this and see about getting it fixed.

**Comment by dodona2** [comment]
I can confirm that running Mint-x under Fedora25. Guess it is a problem with the most recent gtk3 libs. In that case: 3.22.15

**Comment by JosephMcc** [comment]
> I can confirm that running Mint-x under Fedora25. Guess it is a problem with the most recent gtk3 libs. In that case: 3.22.15

Mint-X only supports gtk3.18
