### ISSUE TITLE
a minor color modification issue in Mint-X-Aqua (and others?) 

### ISSUE THREAD

**Issue by Sadi58** [linuxmint/mint-themes-gtk3#84]
I think the green colors "#9ab87c" and "#4e9a06" in "./gtk-3.0/gtk-main-common.css" and "./gtk-3.0/gtk-widgets.css" should also be changed like others (if this wasn't deliberate).
I changed them to "#6cabcd" and "#288afc" for Mint-X-Aqua e.g. creating an aqua-blue bgcolor (#4e9a06) for infobars in Nemo folders like Trash, Actions and Scripts.

**Comment by JosephMcc** [comment]
It is intentional to keep the infobars similar in all variations. Otherwise in themes like Mint-X-Red you would end up with general infobars being red when we want to reserve them for warning or error types.

**Comment by Sadi58** [comment]
Understood. Thanks.
