### ISSUE TITLE
Themes broken by gtk3 updates

### ISSUE THREAD

**Issue by smilesbright** [linuxmint/mint-themes-gtk3#85]
Please update these gtk themes to be compatible with gtk 3.2+ so that individuals with newer versions of gtk can enjoy them :) They are broken in Fedora Cinnamon :(

**Comment by JosephMcc** [comment]
We will when we need them for Mint.

**Comment by dodona2** [comment]
I fully subscribe to smilesbright comment. Better do the update than others do fork.

**Comment by mtwebster** [comment]
It's easy to agree when you don't understand the implications.  As a general rule, we do not multi-track (meaning, supporting multiple versions simultaneously.)  Fixing themes to be fully compatible with the latest GTK will completely break them for the version Mint is currently on (3.18,) and there is too much other maintenance required to other packages to make this any sort of priority until prepping for Mint 19 (early next year.)

It has been thus for a very long time.  It's unfortunate that themes get broken like this so frequently (the change to Gtk 3.20+ support is quite extreme)

Now, if someone were to make the effort and do the fixes and make a PR, I'd probably be willing to make a branch for development (which upstream maintainers or users could point to if they wanted) - this happens occasionally.  Though, prior to this, theme breaks were usually much more mild.  As I said, 3.20 was a doozy.
